// Virtual Functions

/*
Recall that as a parameter, a class object can be passed either by value or by reference.
Earlier chapters also said that the types of the actual and formal parameters must
match. However, in the case of classes, C++ allows the user to pass an object of a
derived class to a formal parameter of the base class type. This is because the derived
class has the base class as its foundation. The formal parameter recognizes the base
class portion of the derived class and allows it to pass.
*/

#include <iostream>

using namespace std ;

/*
<1>
First, let us discuss the case in which the formal parameter is either a reference 
parameter or a pointer. To be specific, let us consider the following classes:
*/
class petType
{
public:
    void print() const ;
    petType(string n = "") ;
private:
    string name ;
} ;

class dogType: public petType
{
public:
    void print() const ;
    dogType(string n = "", string b = "") ;
private:
    string breed ;
} ;

/*
<3>
Consider the following function in a user program (client code):
*/
void callPrint(petType& p)
{
    p.print() ; // <-- petType's print() or dogType's print()?
}

/*
<4>
The function callPrint has a formal reference parameter p of type petType. You
can call the function callPrint by using an object of either type petType or type
dogType as a parameter. Moreover, the body of the function callPrint calls the
member function print. Consider the following function main:
*/
int main()
{
    petType pet("Lucky") ;                    //Line 3
    dogType dog("Tommy", "German Shepherd") ; //Line 4

    pet.print() ;                             //Line 5
    cout << endl ;                            //Line 6
    
    dog.print() ;                             //Line 7
    cout << "*** Calling the function callPrint ***"
        << endl ;                             //Line 8
    
    callPrint(pet) ;                          //Line 9
    cout << endl ;                            //Line 10
    
    callPrint(dog) ;                          //Line 11
    cout << endl ;                            //Line 12

    return 0 ;

    /*
    <5>
    The statements in Lines 3 through 8 are quite straightforward. Let us look at the
    statements in Lines 9 and 11. The statement in Line 9 calls the function callPrint
    and passes the object pet as the parameter; it generates the fourth line of the output.
    The statement in Line 11 also calls the function callPrint but passes the object
    dog as the parameter; it generates the fifth line of the output. The output generated
    by the statements in Lines 9 and 11 shows only the value of name, even though each
    time a different class object was passed as a parameter. Because in Line 11, object
    dog is passed as a parameter to the function callPrint, one would expect that the
    output generated by the statement in Line 11 should be the same as the second line
    of the output. 
    
    What actually occurred is that for both statements (Lines 9 and 11),
    the member function print of the base class petType was executed. This is due to
    the fact that the binding of the member function print in the body of the function
    callPrint occurred at compile time. Because the formal parameter p of the function
    callPrint is of type petType, the compiler associates the function print of the
    class petType for the statement p.print();. More specifically, in compile-time
    binding, the necessary code to call a specific function is generated by the compiler.
    (Compile-time binding is also known as "static binding" or "early binding".)

    For the statement in Line 11, the actual parameter is of type dogType. Thus, when the
    body of the function callPrint executes, logically the print function of object dog
    should execute, which is not the case.

    So, during program execution, how does C++ correct this problem of making the call 
    to the appropriate function? 
    
    C++ corrects this problem by providing the mechanism of "virtual functions". 
    The binding of virtual functions occurs at program execution time, not at compile time. 
    This kind of binding is called "run-time binding", late binding, or dynamic binding. 
    More formally, in run-time binding, the compiler does not generate the code to call 
    a specific function. Instead, it generates enough information to enable the run-time 
    system to generate the specific code for the appropriate function call. 
    Run-time binding is also known as "dynamic binding".

    */
}

/*
<2>
The class petType has three members. The class dogType is derived from the class
petType and has three members of its own. Both classes have a member function print.
Suppose that the definitions of the member functions of both classes are as follows:
*/
void petType::print() const
{
    cout << "Name: " << name ;
}

petType::petType(string n)
{
    name = n ;
}

void dogType::print() const
{
    petType::print() ;
    cout << ", Breed: " << breed << endl ;
}

dogType:: dogType(string n, string b): petType(n)
{
    breed = b ;
}
